#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDDRESTAURANTE")]
	public partial class DCRestauranteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcarta(carta instance);
    partial void Updatecarta(carta instance);
    partial void Deletecarta(carta instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertplato(plato instance);
    partial void Updateplato(plato instance);
    partial void Deleteplato(plato instance);
    partial void Insertrol(rol instance);
    partial void Updaterol(rol instance);
    partial void Deleterol(rol instance);
    #endregion
		
		public DCRestauranteDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.BDDRESTAURANTEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCRestauranteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCRestauranteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCRestauranteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCRestauranteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<carta> cartas
		{
			get
			{
				return this.GetTable<carta>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuarios
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<plato> platos
		{
			get
			{
				return this.GetTable<plato>();
			}
		}
		
		public System.Data.Linq.Table<rol> rols
		{
			get
			{
				return this.GetTable<rol>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carta")]
	public partial class carta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_carta;
		
		private string _descripcion_carta;
		
		private System.DateTime _fecha_carta;
		
		private char _estado_carta;
		
		private EntitySet<plato> _platos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cartaChanging(int value);
    partial void Onid_cartaChanged();
    partial void Ondescripcion_cartaChanging(string value);
    partial void Ondescripcion_cartaChanged();
    partial void Onfecha_cartaChanging(System.DateTime value);
    partial void Onfecha_cartaChanged();
    partial void Onestado_cartaChanging(char value);
    partial void Onestado_cartaChanged();
    #endregion
		
		public carta()
		{
			this._platos = new EntitySet<plato>(new Action<plato>(this.attach_platos), new Action<plato>(this.detach_platos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_carta
		{
			get
			{
				return this._id_carta;
			}
			set
			{
				if ((this._id_carta != value))
				{
					this.Onid_cartaChanging(value);
					this.SendPropertyChanging();
					this._id_carta = value;
					this.SendPropertyChanged("id_carta");
					this.Onid_cartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_carta", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion_carta
		{
			get
			{
				return this._descripcion_carta;
			}
			set
			{
				if ((this._descripcion_carta != value))
				{
					this.Ondescripcion_cartaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_carta = value;
					this.SendPropertyChanged("descripcion_carta");
					this.Ondescripcion_cartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_carta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_carta
		{
			get
			{
				return this._fecha_carta;
			}
			set
			{
				if ((this._fecha_carta != value))
				{
					this.Onfecha_cartaChanging(value);
					this.SendPropertyChanging();
					this._fecha_carta = value;
					this.SendPropertyChanged("fecha_carta");
					this.Onfecha_cartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_carta", DbType="Char(1) NOT NULL")]
		public char estado_carta
		{
			get
			{
				return this._estado_carta;
			}
			set
			{
				if ((this._estado_carta != value))
				{
					this.Onestado_cartaChanging(value);
					this.SendPropertyChanging();
					this._estado_carta = value;
					this.SendPropertyChanged("estado_carta");
					this.Onestado_cartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carta_plato", Storage="_platos", ThisKey="id_carta", OtherKey="id_carta")]
		public EntitySet<plato> platos
		{
			get
			{
				return this._platos;
			}
			set
			{
				this._platos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_platos(plato entity)
		{
			this.SendPropertyChanging();
			entity.carta = this;
		}
		
		private void detach_platos(plato entity)
		{
			this.SendPropertyChanging();
			entity.carta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nombre_usuario;
		
		private string _email_usuario;
		
		private string _pass_usuario;
		
		private System.DateTime _fecha_usuario;
		
		private char _estado_usuario;
		
		private System.Nullable<int> _id_rol;
		
		private EntityRef<rol> _rol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void Onemail_usuarioChanging(string value);
    partial void Onemail_usuarioChanged();
    partial void Onpass_usuarioChanging(string value);
    partial void Onpass_usuarioChanged();
    partial void Onfecha_usuarioChanging(System.DateTime value);
    partial void Onfecha_usuarioChanged();
    partial void Onestado_usuarioChanging(char value);
    partial void Onestado_usuarioChanged();
    partial void Onid_rolChanging(System.Nullable<int> value);
    partial void Onid_rolChanged();
    #endregion
		
		public usuario()
		{
			this._rol = default(EntityRef<rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email_usuario
		{
			get
			{
				return this._email_usuario;
			}
			set
			{
				if ((this._email_usuario != value))
				{
					this.Onemail_usuarioChanging(value);
					this.SendPropertyChanging();
					this._email_usuario = value;
					this.SendPropertyChanged("email_usuario");
					this.Onemail_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_usuario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string pass_usuario
		{
			get
			{
				return this._pass_usuario;
			}
			set
			{
				if ((this._pass_usuario != value))
				{
					this.Onpass_usuarioChanging(value);
					this.SendPropertyChanging();
					this._pass_usuario = value;
					this.SendPropertyChanged("pass_usuario");
					this.Onpass_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_usuario", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_usuario
		{
			get
			{
				return this._fecha_usuario;
			}
			set
			{
				if ((this._fecha_usuario != value))
				{
					this.Onfecha_usuarioChanging(value);
					this.SendPropertyChanging();
					this._fecha_usuario = value;
					this.SendPropertyChanged("fecha_usuario");
					this.Onfecha_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_usuario", DbType="Char(1) NOT NULL")]
		public char estado_usuario
		{
			get
			{
				return this._estado_usuario;
			}
			set
			{
				if ((this._estado_usuario != value))
				{
					this.Onestado_usuarioChanging(value);
					this.SendPropertyChanging();
					this._estado_usuario = value;
					this.SendPropertyChanged("estado_usuario");
					this.Onestado_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int")]
		public System.Nullable<int> id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					if (this._rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rol_usuario", Storage="_rol", ThisKey="id_rol", OtherKey="id_rol", IsForeignKey=true)]
		public rol rol
		{
			get
			{
				return this._rol.Entity;
			}
			set
			{
				rol previousValue = this._rol.Entity;
				if (((previousValue != value) 
							|| (this._rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._rol.Entity = null;
						previousValue.usuarios.Remove(this);
					}
					this._rol.Entity = value;
					if ((value != null))
					{
						value.usuarios.Add(this);
						this._id_rol = value.id_rol;
					}
					else
					{
						this._id_rol = default(Nullable<int>);
					}
					this.SendPropertyChanged("rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cliente")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _nombres_cliente;
		
		private string _dni_cliente;
		
		private string _direccion_cliente;
		
		private string _ttelefono_cliente;
		
		private string _email_cliente;
		
		private System.DateTime _fecha_cliente;
		
		private char _estado_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onnombres_clienteChanging(string value);
    partial void Onnombres_clienteChanged();
    partial void Ondni_clienteChanging(string value);
    partial void Ondni_clienteChanged();
    partial void Ondireccion_clienteChanging(string value);
    partial void Ondireccion_clienteChanged();
    partial void Onttelefono_clienteChanging(string value);
    partial void Onttelefono_clienteChanged();
    partial void Onemail_clienteChanging(string value);
    partial void Onemail_clienteChanged();
    partial void Onfecha_clienteChanging(System.DateTime value);
    partial void Onfecha_clienteChanged();
    partial void Onestado_clienteChanging(char value);
    partial void Onestado_clienteChanged();
    #endregion
		
		public cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres_cliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombres_cliente
		{
			get
			{
				return this._nombres_cliente;
			}
			set
			{
				if ((this._nombres_cliente != value))
				{
					this.Onnombres_clienteChanging(value);
					this.SendPropertyChanging();
					this._nombres_cliente = value;
					this.SendPropertyChanged("nombres_cliente");
					this.Onnombres_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_cliente", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string dni_cliente
		{
			get
			{
				return this._dni_cliente;
			}
			set
			{
				if ((this._dni_cliente != value))
				{
					this.Ondni_clienteChanging(value);
					this.SendPropertyChanging();
					this._dni_cliente = value;
					this.SendPropertyChanged("dni_cliente");
					this.Ondni_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_cliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion_cliente
		{
			get
			{
				return this._direccion_cliente;
			}
			set
			{
				if ((this._direccion_cliente != value))
				{
					this.Ondireccion_clienteChanging(value);
					this.SendPropertyChanging();
					this._direccion_cliente = value;
					this.SendPropertyChanged("direccion_cliente");
					this.Ondireccion_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttelefono_cliente", DbType="VarChar(10)")]
		public string ttelefono_cliente
		{
			get
			{
				return this._ttelefono_cliente;
			}
			set
			{
				if ((this._ttelefono_cliente != value))
				{
					this.Onttelefono_clienteChanging(value);
					this.SendPropertyChanging();
					this._ttelefono_cliente = value;
					this.SendPropertyChanged("ttelefono_cliente");
					this.Onttelefono_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_cliente", DbType="VarChar(100)")]
		public string email_cliente
		{
			get
			{
				return this._email_cliente;
			}
			set
			{
				if ((this._email_cliente != value))
				{
					this.Onemail_clienteChanging(value);
					this.SendPropertyChanging();
					this._email_cliente = value;
					this.SendPropertyChanged("email_cliente");
					this.Onemail_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cliente", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_cliente
		{
			get
			{
				return this._fecha_cliente;
			}
			set
			{
				if ((this._fecha_cliente != value))
				{
					this.Onfecha_clienteChanging(value);
					this.SendPropertyChanging();
					this._fecha_cliente = value;
					this.SendPropertyChanged("fecha_cliente");
					this.Onfecha_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_cliente", DbType="Char(1) NOT NULL")]
		public char estado_cliente
		{
			get
			{
				return this._estado_cliente;
			}
			set
			{
				if ((this._estado_cliente != value))
				{
					this.Onestado_clienteChanging(value);
					this.SendPropertyChanging();
					this._estado_cliente = value;
					this.SendPropertyChanged("estado_cliente");
					this.Onestado_clienteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.plato")]
	public partial class plato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_plato;
		
		private string _nombre_plato;
		
		private string _descripcion_plato;
		
		private decimal _precio_plato;
		
		private string _imagen_plato;
		
		private System.DateTime _fecha_plato;
		
		private char _estado_plato;
		
		private System.Nullable<int> _id_carta;
		
		private EntityRef<carta> _carta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_platoChanging(int value);
    partial void Onid_platoChanged();
    partial void Onnombre_platoChanging(string value);
    partial void Onnombre_platoChanged();
    partial void Ondescripcion_platoChanging(string value);
    partial void Ondescripcion_platoChanged();
    partial void Onprecio_platoChanging(decimal value);
    partial void Onprecio_platoChanged();
    partial void Onimagen_platoChanging(string value);
    partial void Onimagen_platoChanged();
    partial void Onfecha_platoChanging(System.DateTime value);
    partial void Onfecha_platoChanged();
    partial void Onestado_platoChanging(char value);
    partial void Onestado_platoChanged();
    partial void Onid_cartaChanging(System.Nullable<int> value);
    partial void Onid_cartaChanged();
    #endregion
		
		public plato()
		{
			this._carta = default(EntityRef<carta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_plato", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_plato
		{
			get
			{
				return this._id_plato;
			}
			set
			{
				if ((this._id_plato != value))
				{
					this.Onid_platoChanging(value);
					this.SendPropertyChanging();
					this._id_plato = value;
					this.SendPropertyChanged("id_plato");
					this.Onid_platoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_plato", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_plato
		{
			get
			{
				return this._nombre_plato;
			}
			set
			{
				if ((this._nombre_plato != value))
				{
					this.Onnombre_platoChanging(value);
					this.SendPropertyChanging();
					this._nombre_plato = value;
					this.SendPropertyChanged("nombre_plato");
					this.Onnombre_platoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_plato", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion_plato
		{
			get
			{
				return this._descripcion_plato;
			}
			set
			{
				if ((this._descripcion_plato != value))
				{
					this.Ondescripcion_platoChanging(value);
					this.SendPropertyChanging();
					this._descripcion_plato = value;
					this.SendPropertyChanged("descripcion_plato");
					this.Ondescripcion_platoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_plato", DbType="Decimal(8,2) NOT NULL")]
		public decimal precio_plato
		{
			get
			{
				return this._precio_plato;
			}
			set
			{
				if ((this._precio_plato != value))
				{
					this.Onprecio_platoChanging(value);
					this.SendPropertyChanging();
					this._precio_plato = value;
					this.SendPropertyChanged("precio_plato");
					this.Onprecio_platoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen_plato", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string imagen_plato
		{
			get
			{
				return this._imagen_plato;
			}
			set
			{
				if ((this._imagen_plato != value))
				{
					this.Onimagen_platoChanging(value);
					this.SendPropertyChanging();
					this._imagen_plato = value;
					this.SendPropertyChanged("imagen_plato");
					this.Onimagen_platoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_plato", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_plato
		{
			get
			{
				return this._fecha_plato;
			}
			set
			{
				if ((this._fecha_plato != value))
				{
					this.Onfecha_platoChanging(value);
					this.SendPropertyChanging();
					this._fecha_plato = value;
					this.SendPropertyChanged("fecha_plato");
					this.Onfecha_platoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_plato", DbType="Char(1) NOT NULL")]
		public char estado_plato
		{
			get
			{
				return this._estado_plato;
			}
			set
			{
				if ((this._estado_plato != value))
				{
					this.Onestado_platoChanging(value);
					this.SendPropertyChanging();
					this._estado_plato = value;
					this.SendPropertyChanged("estado_plato");
					this.Onestado_platoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carta", DbType="Int")]
		public System.Nullable<int> id_carta
		{
			get
			{
				return this._id_carta;
			}
			set
			{
				if ((this._id_carta != value))
				{
					if (this._carta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cartaChanging(value);
					this.SendPropertyChanging();
					this._id_carta = value;
					this.SendPropertyChanged("id_carta");
					this.Onid_cartaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carta_plato", Storage="_carta", ThisKey="id_carta", OtherKey="id_carta", IsForeignKey=true)]
		public carta carta
		{
			get
			{
				return this._carta.Entity;
			}
			set
			{
				carta previousValue = this._carta.Entity;
				if (((previousValue != value) 
							|| (this._carta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carta.Entity = null;
						previousValue.platos.Remove(this);
					}
					this._carta.Entity = value;
					if ((value != null))
					{
						value.platos.Add(this);
						this._id_carta = value.id_carta;
					}
					else
					{
						this._id_carta = default(Nullable<int>);
					}
					this.SendPropertyChanged("carta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rol")]
	public partial class rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rol;
		
		private string _descripcion_rol;
		
		private System.DateTime _fecha_rol;
		
		private char _estado_rol;
		
		private EntitySet<usuario> _usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rolChanging(int value);
    partial void Onid_rolChanged();
    partial void Ondescripcion_rolChanging(string value);
    partial void Ondescripcion_rolChanged();
    partial void Onfecha_rolChanging(System.DateTime value);
    partial void Onfecha_rolChanged();
    partial void Onestado_rolChanging(char value);
    partial void Onestado_rolChanged();
    #endregion
		
		public rol()
		{
			this._usuarios = new EntitySet<usuario>(new Action<usuario>(this.attach_usuarios), new Action<usuario>(this.detach_usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_rol", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion_rol
		{
			get
			{
				return this._descripcion_rol;
			}
			set
			{
				if ((this._descripcion_rol != value))
				{
					this.Ondescripcion_rolChanging(value);
					this.SendPropertyChanging();
					this._descripcion_rol = value;
					this.SendPropertyChanged("descripcion_rol");
					this.Ondescripcion_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_rol", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_rol
		{
			get
			{
				return this._fecha_rol;
			}
			set
			{
				if ((this._fecha_rol != value))
				{
					this.Onfecha_rolChanging(value);
					this.SendPropertyChanging();
					this._fecha_rol = value;
					this.SendPropertyChanged("fecha_rol");
					this.Onfecha_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_rol", DbType="Char(1) NOT NULL")]
		public char estado_rol
		{
			get
			{
				return this._estado_rol;
			}
			set
			{
				if ((this._estado_rol != value))
				{
					this.Onestado_rolChanging(value);
					this.SendPropertyChanging();
					this._estado_rol = value;
					this.SendPropertyChanged("estado_rol");
					this.Onestado_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rol_usuario", Storage="_usuarios", ThisKey="id_rol", OtherKey="id_rol")]
		public EntitySet<usuario> usuarios
		{
			get
			{
				return this._usuarios;
			}
			set
			{
				this._usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_usuarios(usuario entity)
		{
			this.SendPropertyChanging();
			entity.rol = this;
		}
		
		private void detach_usuarios(usuario entity)
		{
			this.SendPropertyChanging();
			entity.rol = null;
		}
	}
}
#pragma warning restore 1591
